#!/usr/bin/env node
var nomnom     = require('nomnom');

nomnom.script('scuttlebot').nocolors()
nomnom.command('serve')
  .help('Starts the scuttlebot server.')
  .options({
    daemon: {
      flag: true,
      abbr: 'd',
      help: 'Run the server in the background as a daemon.'
    },
    port: {
      help: 'Sets the port for the rpc server.',
      default: 2000
    }
  })
  .callback(require('./lib/index').start);
nomnom.command('stop')
  .help('Stops the web-server daemon if it\'s active.')
  .callback(require('./lib/index').stop);
nomnom.parse();